### ISSUE TITLE
where is output function "categories"?

### ISSUE THREAD

**Issue by EastNight** [Cultrarius/UE4_MagicConsole#1]
Hi,I want to use the original function of "Output log". But I can't find the “categories" selection . So how can i  add the orignal function ?

**Comment by melMass** [comment]
I'm not sure what you mean but  under the options you can add custom categories:

![image](https://user-images.githubusercontent.com/7041726/70397666-7dc5bb00-1a14-11ea-8dc9-844c81348d80.png)
