### ISSUE TITLE
Packaging Failed with brand new Project on 4.24.1

### ISSUE THREAD

**Issue by JimPhoenix** [Cultrarius/UE4_MagicConsole#3]
**Repro:**

1. Create a brand new 4.24 project from the Epic Launcher
2. Enable the Plugin & Restart the Editor
3. Try to build the Project
4. Packaging Failed

`UATHelper: Packaging (Windows (64-bit)): Running AutomationTool...
UATHelper: Packaging (Windows (64-bit)): Parsing command line: -ScriptsForProject="F:/Unreal Engine 4/Project Test Field/Packaging_Test_424/Packaging_Test_424.uproject" BuildCookRun -nocompile -nocompileeditor -installed -nop4 -project="F:/Unreal Engine 4/Project Test Field/Packaging_Test_424/Packaging_Test_424.uproject" -cook -stage -archive -archivedirecto
ry="F:/Unreal Engine 4/Project Test Field/Packaging_Test_424/_GameBuild" -package -ue4exe="F:\Unreal Engine 4\Engine\UE_4.24\Engine\Binaries\Win64\UE4Editor-Cmd.exe" -pak -prereqs -nodebuginfo -targetplatform=Win64 -build -clientconfig=Development -utf8output
UATHelper: Packaging (Windows (64-bit)): Setting up ProjectParams for F:\Unreal Engine 4\Project Test Field\Packaging_Test_424\Packaging_Test_424.uproject
UATHelper: Packaging (Windows (64-bit)): Packaging_Test_424.uproject requires a temporary target.cs to be generated (ActionsExtension plugin is enabled)
UATHelper: Packaging (Windows (64-bit)): ********** BUILD COMMAND STARTED **********
UATHelper: Packaging (Windows (64-bit)): Running: F:\Unreal Engine 4\Engine\UE_4.24\Engine\Binaries\DotNET\UnrealBuildTool.exe Packaging_Test_424 Win64 Development -Project="F:\Unreal Engine 4\Project Test Field\Packaging_Test_424\Packaging_Test_424.uproject"  "F:\Unreal Engine 4\Project Test Field\Packaging_Test_424\Packaging_Test_424.uproject" -NoUBTMakefi
les  -remoteini="F:\Unreal Engine 4\Project Test Field\Packaging_Test_424" -skipdeploy -Manifest="F:\Unreal Engine 4\Project Test Field\Packaging_Test_424\Intermediate\Build\Manifest.xml" -NoHotReload -log="C:\Users\Jim\AppData\Roaming\Unreal Engine\AutomationTool\Logs\F+Unreal+Engine+4+Engine+UE_4.24\UBT-Packaging_Test_424-Win64-Development.txt"
UATHelper: Packaging (Windows (64-bit)):   ERROR: Unable to instantiate module 'UnrealEd': Unable to instantiate UnrealEd module for non-editor targets.
UATHelper: Packaging (Windows (64-bit)):          (referenced via Target -> ConsoleEnhanced.Build.cs)
PackagingResults: Error: Unable to instantiate module 'UnrealEd': Unable to instantiate UnrealEd module for non-editor targets.
UATHelper: Packaging (Windows (64-bit)): Took 1,0737787s to run UnrealBuildTool.exe, ExitCode=5
UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool failed. See log for more details. (C:\Users\Jim\AppData\Roaming\Unreal Engine\AutomationTool\Logs\F+Unreal+Engine+4+Engine+UE_4.24\UBT-Packaging_Test_424-Win64-Development.txt)
UATHelper: Packaging (Windows (64-bit)): AutomationTool exiting with ExitCode=5 (5)
UATHelper: Packaging (Windows (64-bit)): BUILD FAILED
PackagingResults: Error: Unknown Error`

**Comment by nonlin** [comment]
Did you ever solve this?

**Comment by JimPhoenix** [comment]
Sadly no. :(

**Comment by DieGrysWolf** [comment]
Just bumping this, any success?

Have the same issue with 4.24.3

**Comment by nonlin** [comment]
Seems like if you get this error it is because you are trying to package Editor specific content/modules/code for runtime use which is not allowed by Epic in there terms of usage. 

You will have to not include modules/code that are for Editor use only as it will throw this error when you try to package. 

As it states "'UnrealEd': Unable to instantiate UnrealEd module for non-editor targets"

Epic doesn't want you too. 

I ran into this trying to use datasmith editor code at runtime for a packaged build. Can't.

**Comment by GitHub-NetFly** [comment]
The plugin does not need to participate in the packaging process, because it is a functional extension of the editor.

Solution: Find ConsoleEnhanced.uplugin

change into:
	"Modules": [
    {
      "Name": "ConsoleEnhanced",
      **"Type": "Editor",**
      "LoadingPhase": "Default",
      "WhitelistPlatforms": [
        "Win64",
        "Win32"
      ]
    }
	]

**Comment by AliElSaleh** [comment]
I'll create a pull request to fix this

**Comment by CanisHelix** [comment]
PR #4 does not fix this problem, @GitHub-NetFly's suggestion actually fixes this problem in 4.25+ source builds.

**Comment by CMUnreal** [comment]
You may have to upgrade the project to a C++ project to resolve this issue. 

".uproject requires a temporary target.cs to be generated"
