### ISSUE TITLE
Anti Spam Regex cannot be customized (4.25)

### ISSUE THREAD

**Issue by DevKevinYG** [Cultrarius/UE4_MagicConsole#5]
Hi, sorry if this is actually not an issue. But whenever i try to modify the Anti Spam Regex attribute in the settings section, the plugin will only recognize the first string "(last play command: )" and everything else is removed (including the extra strings).

Repro Steps:

1 - Add the plugin to a new project
2 - Go to ProjectSettings>Plugins>Output Log Pro>AntiSpamRegex and modify the string.
3 - The settings is now saved to the project's DefaultEngine.ini. The settings seems to be saved correctly, using "|" as a separator.
4 - Restart the editor and go to Output Log Pro settings. Only the first string "(last play command: )" will be enabled.

Also, it's worth mentioning that i'm using a US International Keyboard layout, i don't know if that could affect. It seems that the issue is the "|" separator.

**Comment by OdinVex** [comment]
> Hi, sorry if this is actually not an issue. But whenever i try to modify the Anti Spam Regex attribute in the settings section, the plugin will only recognize the first string "(last play command: )" and everything else is removed (including the extra strings).
> 
> Repro Steps:
> 
> 1 - Add the plugin to a new project
> 2 - Go to ProjectSettings>Plugins>Output Log Pro>AntiSpamRegex and modify the string.
> 3 - The settings is now saved to the project's DefaultEngine.ini. The settings seems to be saved correctly, using "|" as a separator.
> 4 - Restart the editor and go to Output Log Pro settings. Only the first string "(last play command: )" will be enabled.
> 
> Also, it's worth mentioning that i'm using a US International Keyboard layout, i don't know if that could affect. It seems that the issue is the "|" separator.

Not to necro bump/raise, but it is a regex statement and is processed entirely as-is. Correct patterning is imperative. Perhaps double-checking your regex statement with many online processors to help verify it? I'd recommend closing the _Issue_ for now?

*Edit* On a side note, | is a regex command for “or”. If it is actually being processed accidentally, that's a bug.
