### ISSUE TITLE
Is naming consolidation needed?

### ISSUE THREAD

**Issue by OdinVex** [Cultrarius/UE4_MagicConsole#9]
I see references to "OutputLog Pro" and "OutputLogPlus" (not to mention the project name on _Git_...and the _Epic Marketplace_) and I'm wondering if they should be updated. This would force a one-time reset for end-users if the _Settings_ path is changed.

**Comment by Cultrarius** [comment]
There are a lot of downsides to this with very little benefit, so not going to happen. Sorry.

**Comment by OdinVex** [comment]
Not really, I did it months ago myself, but whatever.

**Comment by Cultrarius** [comment]
Then I probably misunderstood what you meant. I thought you wanted to changed the names of the git project, plugin, marketplace, documentation, etc. so they all are the same. That would be a lot of work.
